# Nightly Build & Pre-release
name: "Nightly"

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '0 5 * * *'

env:
  NIGHTLY_TAG: "v3.0.0-beta-nightly"
  NIGHTLY_NAME: "3.0.0 beta nightly"
  NIGHTLY_BODY: |
    This is the current Polished Crystal 3.0.0 *beta* release. The assets all have an 8-character "commit hash" at the end to identify the exact code they're built from.

    The **.gbc** assets are ROMs. If you just want to play the game, download one (regular or `-faithful`) and load it in [BGB](https://bgb.bircd.org/), [mGBA](https://mgba.io/), [Gambatte](https://github.com/sinamas/gambatte), or another accurate Game Boy Color emulator. (***Do not use VBA*** or VBA-M.)

    The **.sym** assets are "symbol files". They're useful for debugging, or for [discovering cheat codes](https://github.com/pret/pokecrystal/wiki/Discovering-GameShark-cheat-codes), although cheats are *not* officially supported and may cause bugs or crashes. (Do ***not*** ask the developers for cheat codes.)

    The **.bsp** asset is a [BSP](https://github.com/aaaaaa123456789/bsp) save file patch in case you need to upgrade a save file from an older 3.0.0 beta build, using a patcher like the one for [Pokémon Prism](http://pokemonprism.com/patcher.html).

    The **polisheddebug** assets are ROMs and symbol files with extra features to help debug the game. Do ***not*** download these to just play with; use them to help the developers diagnose and fix bugs, or create new features.

jobs:
  build:
    name: "Nightly"
    uses: itsdarsh/polishedcrystal/.github/workflows/build.yml@master
  release:
    name: "Nightly / Release"
    runs-on: ubuntu-latest
    needs: build
    steps:
      # SET ENVIRONMENT VARIABLES
      - id: set-env-var
        name: "Set environment variables"
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      # INSTALL DEPENDENCIES
      - id: apt-get-depends
        name: "Install dependencies"
        run: |
          sudo apt-get install bison gcc git make python2 -y;
      
      # CHECKOUT REPOSITORY
      - id: checkout-polishedcrystal
        name: "Checkout itsdarsh/polishedcrystal"
        uses: actions/checkout@v3
          
      # DOWNLOAD ALL BUILD ARTIFACTS
      - id: download-polishedcrystal
        name: "Download polishedcrystal"
        uses: actions/download-artifact@v3
        with:
          name: "polishedcrystal"
          path: "./build"
      - id: download-polishedcrystal-faithful
        name: "Download polishedcrystal-faithful"
        uses: actions/download-artifact@v3
        with:
          name: "polishedcrystal-faithful"
          path: "./build"
      - id: download-polishedcrystal-nortc
        name: "Download polishedcrystal-nortc"
        uses: actions/download-artifact@v3
        with:
          name: "polishedcrystal-nortc"
          path: "./build"
      - id: download-polishedcrystal-faithful-nortc
        name: "Download polishedcrystal-faithful-nortc"
        uses: actions/download-artifact@v3
        with:
          name: "polishedcrystal-faithful-nortc"
          path: "./build"
      - id: download-polisheddebug
        name: "Download polisheddebug"
        uses: actions/download-artifact@v3
        with:
          name: "polisheddebug"
          path: "./build"
      - id: download-polisheddebug-faithful
        name: "Download polisheddebug-faithful"
        uses: actions/download-artifact@v3
        with:
          name: "polisheddebug-faithful"
          path: "./build"
      - id: download-polisheddebug-nortc
        name: "Download polisheddebug-nortc"
        uses: actions/download-artifact@v3
        with:
          name: "polisheddebug-nortc"
          path: "./build"
      - id: download-polisheddebug-faithful-nortc
        name: "Download polisheddebug-faithful-nortc"
        uses: actions/download-artifact@v3
        with:
          name: "polisheddebug-faithful-nortc"
          path: "./build"
      - id: download-polishedcrystal-savepatch
        name: "Download polishedcrystal-savepatch"
        uses: actions/download-artifact@v3
        with:
          name: "polishedcrystal-savepatch"
          path: "./build"
      
      # DELETE OLD RELEASE
      - name: Delete old release
        id: delete_release
        uses: jagger27/delete-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NIGHTLY_TAG }}
      - name: Advance nightly tag to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.NIGHTLY_TAG }} -f
          git push --tags -f "https://itsdarsh:$GITHUB_TOKEN@github.com/itsdarsh/polishedcrystal.git"

      # CREATE NEW RELEASE
      - name: Create new release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NIGHTLY_TAG }}
          release_name: ${{ env.NIGHTLY_NAME }}
          body: ${{ env.NIGHTLY_BODY }}
          draft: false
          prerelease: true
          
      # UPLOAD POLISHED CRYSTAL ASSETS
      - name: Upload ROM
        id: upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polishedcrystal-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload SYM
        id: upload-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polishedcrystal-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain
          
      # UPLOAD FAITHFUL ASSETS
      - name: Upload faithful ROM
        id: upload-faithful
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polishedcrystal-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload faithful SYM
        id: upload-faithful-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polishedcrystal-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain

      # UPLOAD NORTC ASSETS
      - name: Upload nortc ROM
        id: upload-nortc
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polishedcrystal-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload nortc SYM
        id: upload-sym-nortc
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polishedcrystal-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain
          
      # UPLOAD FAITHFUL NORTC ASSETS
      - name: Upload faithful nortc ROM
        id: upload-faithful-nortc
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polishedcrystal-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload faithful nortc SYM
        id: upload-faithful-nortc-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polishedcrystal-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain
          
      # UPLOAD DEBUG ASSETS
      - name: Upload debug ROM
        id: upload-debug
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polisheddebug-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload debug SYM
        id: upload-debug-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polisheddebug-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain
          
      # UPLOAD FAITHFUL DEBUG ASSETS
      - name: Upload faithful debug ROM
        id: upload-faithful-debug
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polisheddebug-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload faithful debug SYM
        id: upload-faithful-debug-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polisheddebug-faithful-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain

      # UPLOAD NORTC DEBUG ASSETS
      - name: Upload nortc debug ROM
        id: upload-debug-nortc
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polisheddebug-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload nortc debug SYM
        id: upload-debug-nortc-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polisheddebug-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain
          
      # UPLOAD FAITHFUL NORTC DEBUG ASSETS
      - name: Upload faithful nortc debug ROM
        id: upload-faithful-nortc-debug
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_name: polisheddebug-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          asset_content_type: application/octet-stream
      - name: Upload faithful nortc debug SYM
        id: upload-faithful-nortc-debug-sym
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polisheddebug-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_name: polisheddebug-faithful-nortc-3.0.0-beta-${{ env.SHORT_SHA }}.sym
          asset_content_type: text/plain
          
      # UPLOAD SAVE PATCH
      - name: Upload BSP
        id: upload-bsp
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/polishedcrystal-savepatch-3.0.0-beta-${{ env.SHORT_SHA }}.bsp
          asset_name: polishedcrystal-savepatch-3.0.0-beta-${{ env.SHORT_SHA }}.bsp
          asset_content_type: application/octet-stream
